In [1]:
from eg import get_data

In [2]:
data=get_data()

In [14]:
comments=[]
comment_user_id=[]
post_user_id=[]
for inst in data:
    if inst['comments']:
         comments.extend(inst['comments'])
         comment_user_id.extend(inst['comment_authors'])
         post_user_id.extend(len(inst['comments'])*[inst['user']])

In [18]:
comments

In [21]:
import string

In [20]:
def preprocessing_text(text):
    table=str.maketrans('','',string.punctuation)
    pre_text=[]
    for inst in text:
        sent=""
        words=inst.split(" ")
        for word in words:
            word=word.translate(table)
            if word.isalpha():
                word=word.lower()
                sent+=word
                sent+=" "
                
        pre_text.append(sent.strip())
        
    return pre_text

In [25]:
from tensorflow.keras.preprocessing.text import tokenizer_from_json

In [24]:
with open(r'C:\Desktop\CodeUtsava\Project\api\drugtrafficking\Models\drug_sentiment_tokenizer.json','r')as file:
    tokenizer_json=file.read()

In [26]:
tokenizer=tokenizer_from_json(tokenizer_json)

In [27]:
tokenizer

In [29]:
input_comments=preprocessing_text(comments)

In [30]:
input_comments

In [31]:
inp=tokenizer.texts_to_sequences(input_comments)

In [32]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [34]:
inp_seq=pad_sequences(inp,maxlen=12,padding='post',truncating='post')

In [38]:
inp_seq

array([[  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  1, 396,  20, 244,  16,   4,  25,  79,   0,   0,   0,   0],
       [ 54, 199,  12, 807, 117, 458,  30,   7, 808, 459,   0,   0],
       [  1, 189,   8,   2,  35,   1,   0,   0,   0,   0,   0,   0],
       [  4,   1,   1,  21,  22, 398,   4,  22,  28,  35,   0,   0],
       [244,  16,   4,  25,  28,  35,   0,   0,   0,   0,   0,   0],
       [ 71,  20,  52,  70,  21, 131,   2, 139,  64,   0,   0,   0],
       [ 18,   8,  78,   3,  25, 314,  13, 170, 462,   0,   0,   0],
       [  4,  22,  28,  35,   0,   0,   0,   0,   0,   0,   0,   0],
       [  4,  22,   3, 140,  28,  35,   0,   0,   0,   0,   0,   0],
       [  2,  14,  11,   3, 307,  13, 308, 454,   0,   0,   0,   0],
       [ 28,  64,  24, 267, 302,   4, 559,   0,   0,   0,   0,   0]])

In [37]:
from tensorflow.keras.utils import CustomObjectScope

In [39]:
from CustomLayers.fraction_constraint import FractionConstraint
from CustomLayers.weighted_layer import WeightedLayer

In [40]:
from tensorflow.keras.models import load_model

In [42]:
with CustomObjectScope({'FractionConstraint':FractionConstraint,'WeightedLayer':WeightedLayer}):
    model=load_model(r'C:\Desktop\CodeUtsava\Project\api\drugtrafficking\Models\drug_sentiment_model.h5')

In [43]:
pred=model.predict(inp_seq)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 653ms/step


In [45]:
pred

array([[1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.0000000e+00],
       [4.0017860e-17],
       [1.0000000e+00],
       [1.0000000e+00],
       [1.9221644e-19],
       [1.0000000e+00]], dtype=float32)

In [47]:
import tensorflow as tf

In [50]:
pred=tf.cast(tf.round(pred),tf.int32).numpy()

In [51]:
pred

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1]])

In [54]:
comments

['hey',
 'Please tell me where can i find it',
 'been thinking about diversifying into other drugs a smart move',
 'hey,how much for the drug huh?',
 'I pay whatever you want but i want this drug.',
 'Where can i find this drug',
 'hit me up if you have the latest stash',
 'looking for ways to find inspiration in everyday tasks',
 'I want this drug....',
 'I want to try this drug',
 'The best way to indulge in comfort foods',
 'this stash is better than i expected']

In [52]:
predictions=[p[0] for p in pred]

In [53]:
predictions

[1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1]

In [55]:
drug_dealer=[]
drug_customer=[]
drug_comment=[]
for uid,cid,comm,pred in zip(post_user_id,comment_user_id,comments,predictions):
    if pred==1:
        drug_dealer.append(uid)
        drug_customer.append(cid)
        drug_comment.append(comm)


In [1]:
a=[1,2,3,5]
a.reverse()

In [3]:
reversed(a)

In [5]:
from eg3 import get_entire_data

In [7]:
data=get_entire_data()

In [15]:
a=data[0]['user']

In [16]:
a

31

In [12]:
import json

In [13]:
with open(r'C:\Desktop\CodeUtsava\Project\api\drugtrafficking\Models\susp_user.json','r') as file:
    sus=json.load(file) 

In [17]:
if a in sus:
    print('y')

y


In [2]:
a

[5, 3, 2, 1]

In [56]:
drug_comment

['hey',
 'Please tell me where can i find it',
 'been thinking about diversifying into other drugs a smart move',
 'hey,how much for the drug huh?',
 'I pay whatever you want but i want this drug.',
 'Where can i find this drug',
 'hit me up if you have the latest stash',
 'I want this drug....',
 'I want to try this drug',
 'this stash is better than i expected']

In [57]:
from eg1 import get_data

In [58]:
user_data=get_data()

In [66]:
def get_user_data_from_id(id,keyword):
    data={}
    for inst in user_data:
        if inst['id']==id:
            data[keyword+'_id']=inst['id']
            data[keyword+'_username']=inst['username']
            data[keyword+'_name']=inst['firstname']+' '+inst['surname']
            data[keyword+'_location']=inst['location']
            data[keyword+'_ip_address']=inst['ipaddress']
    return data
            
    

In [63]:
user_data

[{'id': 7,
  'username': 'ghalib',
  'firstname': 'Mirza',
  'surname': 'Ghalib',
  'email': 'ghalib@gmail.com',
  'isOnline': 'no',
  'lastOnline': '1527942645296',
  'ipaddress': '127.0.0.1',
  'location': None},
 {'id': 8,
  'username': 'coldplay',
  'firstname': 'cold',
  'surname': 'play',
  'email': 'coldplay@gmail.com',
  'isOnline': 'no',
  'lastOnline': '',
  'ipaddress': '127.0.0.1',
  'location': None},
 {'id': 10,
  'username': 'noddy',
  'firstname': 'your',
  'surname': 'noddy',
  'email': 'noddy@gmail.com',
  'isOnline': 'no',
  'lastOnline': '',
  'ipaddress': '127.0.0.1',
  'location': None},
 {'id': 11,
  'username': 'nobita',
  'firstname': 'nobita',
  'surname': 'nobi',
  'email': 'nobita@gmail.com',
  'isOnline': 'no',
  'lastOnline': '1524499561897',
  'ipaddress': '127.0.0.1',
  'location': None},
 {'id': 12,
  'username': 'pikachu',
  'firstname': 'your',
  'surname': 'pikachu',
  'email': 'pikachu@gmail.com',
  'isOnline': 'no',
  'lastOnline': '',
  'ipaddress

In [67]:
get_user_data_from_id(35,'drug_dealer')

{'drug_dealer_id': 35,
 'drug_dealer_username': 'teds',
 'drug_dealer_name': 'jyhgfy chbhjh',
 'drug_dealer_location': None,
 'drug_dealer_ip_address': '127.0.0.1'}

In [16]:
len(post_user_id)

In [8]:
len(comments)

In [11]:
len(comment_user_id)

In [2]:
a=[]
if 1 not in a:
    print('u')

In [3]:
data

[{'post_id': 103,
  'user': 31,
  'description': '#powder',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933298648.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 104,
  'user': 31,
  'description': '#drug',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933318839.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 105,
  'user': 31,
  'description': '#marijuana',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933342489.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 106,
  'user': 33,
  'description': '#drug #cocaine',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933516260.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 107,
  'user': 34,
  'description': '#drug #cocaine',
  'im

In [30]:
import json
json.dumps(data)

'[{"post_id": 103, "user": 31, "description": "#powder", "imgSrc": "C:\\\\Desktop\\\\CodeUtsava\\\\React-Instagram-Clone-2.0\\\\dist\\\\posts\\\\instagram_1729933298648.jpg", "location": "", "comments": [], "comment_authors": []}, {"post_id": 104, "user": 31, "description": "#drug", "imgSrc": "C:\\\\Desktop\\\\CodeUtsava\\\\React-Instagram-Clone-2.0\\\\dist\\\\posts\\\\instagram_1729933318839.jpg", "location": "", "comments": [], "comment_authors": []}, {"post_id": 105, "user": 31, "description": "#marijuana", "imgSrc": "C:\\\\Desktop\\\\CodeUtsava\\\\React-Instagram-Clone-2.0\\\\dist\\\\posts\\\\instagram_1729933342489.jpg", "location": "", "comments": [], "comment_authors": []}, {"post_id": 106, "user": 33, "description": "#drug #cocaine", "imgSrc": "C:\\\\Desktop\\\\CodeUtsava\\\\React-Instagram-Clone-2.0\\\\dist\\\\posts\\\\instagram_1729933516260.jpg", "location": "", "comments": [], "comment_authors": []}, {"post_id": 107, "user": 34, "description": "#drug #cocaine", "imgSrc": "C

In [4]:
user_id=[]
img_src=[]
post_id=[]
for inst in data:
    user_id.append(inst['user'])
    img_src.append(inst['imgSrc'])
    post_id.append(inst['post_id'])

In [5]:
user_id

[31, 31, 31, 33, 34]

In [6]:
img_src

['C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933298648.jpg',
 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933318839.jpg',
 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933342489.jpg',
 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933516260.jpg',
 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933741301.jpg']

In [7]:
post_id

[103, 104, 105, 106, 107]

In [8]:
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import CustomObjectScope
from CustomLayers.inception_cell import Inception_cell
from CustomLayers.skip_connection import SkipConnection
from CustomLayers.cosine_annealing_scheduler import CosineAnnealingScheduler

In [9]:
with CustomObjectScope({'Inception_cell':Inception_cell,'SkipConnection':SkipConnection,'CosineAnnealingScheduler':CosineAnnealingScheduler}):
    model=load_model(r'Models\drug_sentiment_img.h5')

In [10]:
def preprocessing_img(img_path):
    img=tf.io.read_file(img_path)
    img=tf.image.decode_jpeg(img,channels=3)
    img=tf.image.resize(img,(256,256))
    img/=255.0
    return img

In [11]:
input_img=[preprocessing_img(img_path) for img_path in img_src]

In [12]:
import numpy as np
input_img=np.array(input_img)

In [13]:
input_img.shape

(5, 256, 256, 3)

In [14]:
pred=model.predict(input_img)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 245ms/step


In [15]:
pred

array([[4.4544257e-05],
       [4.6462836e-05],
       [2.8652481e-03],
       [9.9990171e-01],
       [9.9990171e-01]], dtype=float32)

In [16]:
pred=tf.cast(tf.round(pred),tf.int32)


In [17]:
pred

<tf.Tensor: shape=(5, 1), dtype=int32, numpy=
array([[0],
       [0],
       [0],
       [1],
       [1]])>

In [18]:
pred=pred.numpy()

In [19]:
pred=[p[0] for p in pred]

In [20]:
pred

[0, 0, 0, 1, 1]

In [23]:
blacklist_user=[]
blacklist_post=[]
for uid,pid,img_sentiment in zip(user_id,post_id,pred):
    if img_sentiment==0:
        blacklist_user.append(uid)
        blacklist_post.append(pid)

In [24]:
blacklist_user

[31, 31, 31]

In [25]:
blacklist_post

[103, 104, 105]

In [26]:
blacklist_user=set(blacklist_user)


In [28]:
blacklist_user_info=[]
for inst in data:
    if inst['post_id'] in blacklist_post:
        blacklist_user_info.append(inst)

In [29]:
blacklist_user_info

[{'post_id': 103,
  'user': 31,
  'description': '#powder',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933298648.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 104,
  'user': 31,
  'description': '#drug',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933318839.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []},
 {'post_id': 105,
  'user': 31,
  'description': '#marijuana',
  'imgSrc': 'C:\\Desktop\\CodeUtsava\\React-Instagram-Clone-2.0\\dist\\posts\\instagram_1729933342489.jpg',
  'location': '',
  'comments': [],
  'comment_authors': []}]